//DILARANG MEMPERJUAL BELI SC NYA! MAU REUPLOAD? TARO CREDIT GW TANZA THE MAKERZ. EMANG ANJ LO JUAL SC GW MINIMAL BIKIN SC SENDIRI DECK😂 
#TANZA THE MAKERZ
#+60162276340
#SC BOT V6
THANKS FOR MY SUBSCRIBER DONT FORGET TO SUBSCRIBE MY YOUTUBE CHANNEL TANZA THE MAKERZ